@module io.directory

-- !!!! NOTE !!!!
-- ONLY INCLUDE THIS FILE MANUALLY WHEN YOU REALLY NEED TO. 
-- IT'S AUTOMATICALLY INCLUDED IN IO LIBRARY
--
-- BE SURE TO INCLUDE 'SYSTEM' BEFORE INCLUDING THIS MODULE